FROM python

RUN pip install typer fastapi uvicorn sqlalchemy requests pydantic typing tk
RUN apt-get update && apt-get install -y iproute2 iptables iputils-ping x11vnc xvfb python3-tk eog && rm -rf /var/lib/apt/lists/*


WORKDIR /home/app


COPY . /home/app

COPY client.sh /home/app
RUN chmod +x /home/app/client.sh

EXPOSE 8070

CMD ["sh", "-c", "/home/app/client.sh"]

# CMD ["python", "/home/app/client_app.py"]