version: '3'

services:
  server:
    image: server
    container_name: container_server
    ports:
      - "5001:5000"  # Exponer el puerto del servidor
    volumes:
      - ${PWD}/server:/app/code
      - ${PWD}/logs/container_1:/app/logs
      - ${PWD}/databases/container_server:/app/database
    networks:
      servers:
        ipv4_address: 10.0.11.10  # Asignar una IP fija al servidor
  

  client1:
    image: client
    container_name: client1
    ports:
      - "8501:8501"  # Expone el puerto de Streamlit
    cap_add:
      - NET_ADMIN
    command: /bin/bash
    tty: true
    stdin_open: true  # Exponer el puerto de Streamlit
    volumes:
      - ${PWD}/client:/app/code
      - ${PWD}/logs/client_1:/app/logs
    networks:
      - clients
      # - servers

  client2:
    image: client
    container_name: client2
    cap_add:
      - NET_ADMIN
    privileged: true 
    command: /bin/bash
    ports:
      - "8502:8501"  # Expone el puerto de Streamlit
    tty: true
    stdin_open: true # Exponer otro puerto para un segundo cliente
    volumes:
      - ${PWD}/client:/app/code
      - ${PWD}/logs/client_2:/app/logs
    networks:
      - clients
      # - servers

networks:
  clients:
    external: true  # Ya que la red fue creada por 'setup_docker.sh'
  servers:
    external: true  # Ya que la red fue creada por 'setup_docker.sh'
